#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bundle-BioPerl
version:      2.1.5
version_from: BioPerl.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
